[build]
    command = "export CI=false && yarn build"
    publish = "build"

[context.production]
    [context.production.environment]
        REACT_APP_API_ENV = "production"

[context.staging]
    [context.staging.environment]
        REACT_APP_API_ENV = "staging"

[[headers]]
    for = "/*"
    [headers.values]
    cache-control = '''
        max-age=0,
        must-revalidate'''